In [ ]:
import tensorflow as tf
import numpy as np

## Creating zero dimensional tensor
A zero dimensional tensor is just like a number, it is not an array

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


## 1 dimensional tensor

In [ ]:
tensor_one_d = tf.constant([2, 9, 1])
print(tensor_one_d)

tf.Tensor([2 9 1], shape=(3,), dtype=int32)


## 2D tensor

In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [2, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 2  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


## 3D tensors

In [ ]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
    [2, 5, -1]],

    [[1, 5, 6],
    [2, 3, 8]],

    [[5, 3, 7],
     [6, 3, 6]],

    [[4, 7, 2],
     [6, 2, 5]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 2  5 -1]]

 [[ 1  5  6]
  [ 2  3  8]]

 [[ 5  3  7]
  [ 6  3  6]]

 [[ 4  7  2]
  [ 6  2  5]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_two_d.shape

TensorShape([4, 3])

In [ ]:
tensor_three_d.ndim

3

# 4D tensors

In [ ]:
tensor_4d = tf.constant([
    [
        [[1,2], [4, 32]],
        [[43, 123], [54, 3]]
    ],
    [
        [[65, 24], [78, 98]],
        [[1, 7], [0, 2]]
    ]
])

In [ ]:
tensor_4d.ndim

4

# Changing our data type

In [ ]:
tensor_1_d = tf.constant([2,0,-3,5,95], dtype=tf.float32)
print(tensor_1_d)

tf.Tensor([ 2.  0. -3.  5. 95.], shape=(5,), dtype=float32)


# float16 takes less memories location for storing tensors compared to float32 upwards

In [ ]:
tensor_1_d = tf.constant([2.2,0,-3.0,5.,95], dtype=tf.float16)
print(tensor_1_d)

tf.Tensor([ 2.2  0.  -3.   5.  95. ], shape=(5,), dtype=float16)


# We can convert a float type tensor to an integer type using the tf.cast method

In [ ]:
casted_tensor = tf.cast(tensor_1_d, dtype=tf.int16)
casted_tensor

<tf.Tensor: shape=(5,), dtype=int16, numpy=array([ 2,  0, -3,  5, 95], dtype=int16)>

In [ ]:
#  We can also cast our tensor into a boolean and non zero element would have the same value and zero elements will have the same val
casted_tensor_bool = tf.cast(tensor_1_d, dtype=tf.bool)
casted_tensor_bool

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True, False,  True,  True,  True])>

In [ ]:
tensor_bool = tf.constant([False, True, False])
tensor_bool

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False,  True, False])>

In [ ]:
tensor_string = tf.constant(['Hello World', 'Noooo'])
tensor_string

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Hello World', b'Noooo'], dtype=object)>

# Converting Numpy array into a tensor

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
np_array

array([1, 2, 4])

In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


# The Eye method is used to construct an identity matrix or a batch of matrices

In [ ]:
eye_tensor = tf.eye(
    3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
eye_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
eye_tensor = tf.eye(
    3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
eye_tensor

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])>

In [ ]:
eye_tensor = tf.eye(
    5,
    num_columns=5,
    batch_shape=[2, 2],
    dtype=tf.dtypes.float16,
    name=None
)
eye_tensor

<tf.Tensor: shape=(2, 2, 5, 5), dtype=float16, numpy=
array([[[[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]],

        [[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]]],


       [[[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]],

        [[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]]]], dtype=float16)>

In [ ]:
fill_tensor = tf.fill(
    [1, 3, 4],  5, name=None, layout=None
)
fill_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]], dtype=int32)>

In [ ]:
ones_tensor = tf.ones(
    [2, 3, 4],
    dtype=tf.dtypes.float16,
    name=None,
    layout=None
)
ones_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)>

In [ ]:
ones_like = tf.ones_like(
    fill_tensor, dtype=None, name=None, layout=None
)
ones_like

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [ ]:
zeros_tensor = tf.zeros(
    [2,4],
    dtype=tf.dtypes.int16,
    name=None
)
zeros_tensor

<tf.Tensor: shape=(2, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

# Two ways to get the shape of a tensor

In [ ]:
print(zeros_tensor.shape)

(2, 4)


In [ ]:
print(tf.shape(zeros_tensor))

tf.Tensor([2 4], shape=(2,), dtype=int32)


In [ ]:
tf.rank(zeros_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.size(zeros_tensor, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [ ]:
print(tf.range(1, 6))

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
random_tensor = tf.random.normal(
    [3, 2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[102.48487 ,  99.27274 ],
       [ 99.08806 ,  98.94915 ],
       [ 98.571365,  99.58534 ]], dtype=float32)>

# The  standard deviation in a normal distribution determines how much our values deviate from our mean

# In a uniform distribution, all our values have a probability of being picked

In [ ]:
unform_tensor = tf.random.uniform(
    [5, ],
    minval=5,
    maxval=6,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
unform_tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 5, 5, 5, 5], dtype=int32)>

# Using the set seed, we can create a reproducible sequence of tensors accross multiple calls

In [ ]:
tf.random.set_seed(5)

print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)


# INdexing

In [ ]:
tensor_indexed = tf.constant([3,6,5,3,6,66,7])
tensor_indexed[4:6]
# skip by 2
print(tensor_indexed[1:6:2])

tf.Tensor([ 6  3 66], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  0],
       [ 2,  5, -1],
       [ 1,  5,  6],
       [ 2,  3,  8]], dtype=int32)>

# 2D indexing
tensor_two_d[row, column]
Its similar to using python array index on the shape of the tensor

In [ ]:
print(tensor_two_d[0:3, 0:2])

tf.Tensor(
[[1 2]
 [2 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
print(tensor_two_d[0:3, :])

tf.Tensor(
[[ 1  2  0]
 [ 2  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [ ]:
# The spread operator also means picking up all the indexes
print(tensor_two_d[..., 1])

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


# 3D  Indexing
batch size, row, column
z, y, x

In [ ]:
tensor_three_d

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 2,  5, -1]],

       [[ 1,  5,  6],
        [ 2,  3,  8]],

       [[ 5,  3,  7],
        [ 6,  3,  6]],

       [[ 4,  7,  2],
        [ 6,  2,  5]]], dtype=int32)>

In [ ]:
print(tensor_three_d[0, :, ...])

tf.Tensor(
[[ 1  2  0]
 [ 2  5 -1]], shape=(2, 3), dtype=int32)


# tf.math

In [ ]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

For a complex number a + by, its absolute value is computed as sqrt(a**2 + b**2)
.

In [ ]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

# Basic Arithmetic Operations

In [ ]:
x_1 = tf.constant([2, 3, 4, 5, 6, 45], dtype=tf.int32)
x_2 = tf.constant([7, 1, 4, 52, 3, 5], dtype=tf.int32)
print(tf.add(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.subtract(x_1, x_2))
print(tf.divide(x_1, x_2))

tf.Tensor([ 9  4  8 57  9 50], shape=(6,), dtype=int32)
tf.Tensor([ 14   3  16 260  18 225], shape=(6,), dtype=int32)
tf.Tensor([ -5   2   0 -47   3  40], shape=(6,), dtype=int32)
tf.Tensor([0.28571429 3.         1.         0.09615385 2.         9.        ], shape=(6,), dtype=float64)


## No nan division helps us handle exception like when dividing by 0

In [ ]:
x_1 = tf.constant([4,2], dtype=tf.float32)
x_2 = tf.constant([0,4], dtype=tf.float32)

print(tf.math.divide_no_nan(x_1, x_2))

tf.Tensor([0.  0.5], shape=(2,), dtype=float32)


In [ ]:
x_1 = tf.constant([2, 3, 4, 5, 6, 45], dtype=tf.int32)
x_2 = tf.constant([7], dtype=tf.int32)
# the single val would be stretched x_2 addition shows x_2 os stretched to [7,7,7,7,7,7]
x_2_stretched = tf.constant([7,7,7,7,7,7])
print(tf.add(x_1, x_2))
print(tf.add(x_1, x_2_stretched))

tf.Tensor([ 9 10 11 12 13 52], shape=(6,), dtype=int32)
tf.Tensor([ 9 10 11 12 13 52], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype=tf.float32)
x_2 = tf.constant([[5],[3],[6]], dtype=tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]
 [30. 18. 36. 36. 24. 36.]], shape=(3, 6), dtype=float32)


## tf.math.argmax returns the index of the maximum element in the tensor while argmin returns the index of the min val

# Matrix Multiplication
In matrix multiplication, the number of columns of the first matrix should be the same as the number of rows of the second matrix
Our output becomes the number of the row of the first matrix by the number of column of the second matrix

In [ ]:
x_1 = tf.constant([[1, 2, 0], [3, 5, -1]])
x_2 = tf.constant([[1, 2, 0, 2], [3, 5, -1, 2], [4, 5, 6, 0]])

tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[  7,  12,  -2,   6],
       [ 14,  26, -11,  16]], dtype=int32)>

## Matrix multiplication can als  be done using the @ symbol

In [ ]:
print(x_1@x_2)

tf.Tensor(
[[  7  12  -2   6]
 [ 14  26 -11  16]], shape=(2, 4), dtype=int32)


Tranpose of a matrix

In [ ]:
print(tf.transpose(x_1))

tf.Tensor(
[[ 1  3]
 [ 2  5]
 [ 0 -1]], shape=(3, 2), dtype=int32)


In [ ]:
print(x_2@tf.transpose(x_2))
print(tf.linalg.matmul( x_2, x_2, transpose_a=False, transpose_b=True, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False,
output_type=None, name=None))

tf.Tensor(
[[ 9 17 14]
 [17 39 31]
 [14 31 77]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 9 17 14]
 [17 39 31]
 [14 31 77]], shape=(3, 3), dtype=int32)


In [ ]:
x_1 = tf.constant([
    [1, 2, 0, 2],
     [3, 5, -1, 2],
      [4, 5, 6, 0]
    ])
x_2 = tf.constant([
    [1, 2, 0, 2],
     [3, 5, -1, 2],
      [4, 5, 6, 0],
    [4, 7, -2, 7]
    ])

print(x_1@x_2)

tf.Tensor(
[[ 15  26  -6  20]
 [ 22  40 -15  30]
 [ 43  63  31  18]], shape=(3, 4), dtype=int32)


In [ ]:
x_1 = tf.constant([
    [[2, 0],
    [2, 5]],

    [[5, 6],
    [2, 8]],

    [[5, 7],
     [3, 6]],

    [[4, 2],
     [2, 5]]
])

x_2 = tf.constant([
    [[1, 2, 0],
    [2, 5, -1]],

    [[1, 5, 6],
    [2, 3, 8]],

    [[5, 3, 7],
     [6, 3, 6]],

    [[4, 7, 2],
     [6, 2, 5]]
])
print(x_1@x_2)
print(x_1[1]@x_2[1])

tf.Tensor(
[[[ 2  4  0]
  [12 29 -5]]

 [[17 43 78]
  [18 34 76]]

 [[67 36 77]
  [51 27 57]]

 [[28 32 18]
  [38 24 29]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[17 43 78]
 [18 34 76]], shape=(2, 3), dtype=int32)


# Sparse tensors are mostly made of zeros

# And so much more linear algebra functions can be performed in a tensor. We can check the tensorflow documentation or also watch the yt video https://www.youtube.com/watch?v=IA3WxTTPXqQ&t=8463s